name: cucumber

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run_cucumber:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: run cucumber
        run: cd ./software/firmware && sudo ./run_cucumber.sh -c --parallel
